### ISSUE TITLE
Color of the links

### ISSUE THREAD

**Issue by FMezard** [isawnyu/isaw-papers-ereaders#14]
In order to avoid the blue links, there is black color applied to them. I did not find any way to have the link either black or blue in the ePubs, meaning that if change the color of the whole text (you can chose between several with iBooks for example), the links stay black.

Mobi does not recognize any color in the css and the links stay blue.

**Comment by sfsheath** [comment]
We don't want to spend too much time overcoming the shortcomings of ePub. Anything that looks reasonable is OK. Sounds like Mobi isn't very rich in terms of what you can control so don't put effort there.
